FROM ubuntu 

RUN apt update
RUN apt install -y apache2
RUN apt install -y apache2-utils
RUN apt clean

COPY ./public-html/ /usr/local/apache2/htdocs/
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

RUN apt install python3 pip -y 

COPY api /api

RUN pip install -r /api/requirements.txt --break-system-packages

EXPOSE 80 8081

CMD ["python3", "/api/get_resources.py &"]
CMD ["apache2ctl", "-D", "FOREGROUND"]