services:
  web-server:
    image: sae52-web-server:latest
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
     - 8080:80
  
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  
  pyagent:
    image: sae52-pyagent:latest
    build:
      context: ./pyagent
      dockerfile: Dockerfile
      
    
