services:
  web-server:
    image: sae-52-web-server
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
     - 8080:80
     - 8081:8081
  
  db:
    image: mariadb
    container_name: sae-52-mariadb
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "ss -lnpt | grep 3306"]
      interval: 2s
      retries: 20
      start_period: 5s
      timeout: 5s
    ports:
      - 3306:3306
  
  pyagent:
    image: sae-52-pyagent
    build:
      context: ./pyagent
      dockerfile: Dockerfile
    links:
      - "db"
      - "web-server"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
