{
 "title": "Apache",
 "time": { "from": "2024-10-17T14:28:18.739Z", "to": "2024-10-17T14:46:17.959Z" },
 "panels": [
  {
   "title": "Request Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT duration_per_req, time FROM monitoring.apache2 ORDER BY time DESC LIMIT 60"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT uptime FROM monitoring.apache2 ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Connection number",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT conn_total FROM monitoring.apache2 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Requests /s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Rq/s" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT req_per_sec, time FROM monitoring.apache2 ORDER BY time DESC LIMIT 60 "
    }
   ]
  },
  {
   "title": "Processes Running",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT processes FROM monitoring.apache2 ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Transfer Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT bytes_per_sec, time FROM monitoring.apache2 ORDER BY time DESC LIMIT 60 "
    }
   ]
  }
 ]
}