{
 "title": "Web Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT cpu, time FROM monitoring.data_webserv ORDER BY `time` DESC LIMIT 60 "
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT disk_used FROM monitoring.data_webserv LIMIT 60"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT ramGB, time FROM monitoring.data_webserv ORDER BY `time` DESC LIMIT 60"
    }
   ]
  },
  {
   "title": "Download & Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT dl_speed, ul_speed, time FROM monitoring.data_webserv ORDER BY `time` DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Disk write & read speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "dataset": "monitoring",
     "rawSql": "SELECT disk_read_speed, disk_write_speed, time FROM monitoring.data_webserv ORDER BY `time` DESC LIMIT 60"
    }
   ]
  }
 ]
}